RNA_RES = ["A","U","G","C"]
DNA_RES = ["DA","DT","DG","DC"]

PROTEIN_RES = [
"ALA","ARG","ASN","ASP","CYS","GLU","GLN","GLY",
"HIS","ILE","LEU","LYS","MET","PHE","PRO",
"SER","THR","TRP","TYR","VAL"
]

CONTACT_DISTANCE = 5.0
HBOND_DISTANCE = 3.5
STACK_DISTANCE = 5.0
